fix: Add egress rule update support
terraform-aws-modules/terraform-aws-route53 pull request #107
Opened 2024-06-10 12:37 UTC by renebarbosafl

## Description

This PR complements https://github.com/terraform-aws-modules/terraform-aws-route53/pull/106 by adding a new variable, allowing the submodule to update egress rules

## Motivation and Context

The previous pull request was hardcoding an egress rule allowing All the traffic. Users could want to update these rules as their needs and it's also a security issue.

## Breaking Changes

The default value for of `var.security_group_egress_cidr_blocks` is an empty list, it can cause problems when using inbound resolver-endpoints and not declaring this variable. To fix it, we can do something like:

```hcl
security_group_egress_cidr_blocks = [
  "0.0.0.0/0" # Allow All
]
```
or
```hcl
security_group_egress_cidr_blocks = [
  module.vpc2.vpc_cidr_block # Allow target vpc
] 
```

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

2024-06-14 13:39 UTC, renebarbosafl commented
Hi @antonbabenko, Is there any chance we could get this approved and merged? 
Thank you very much!

2024-08-15 01:00 UTC, renebarbosafl commented
Commenting to remove stale mark.

2024-08-16 19:46 UTC, antonbabenko requested changes
Let's make this change not as a breaking change.

Add support for `ip_address` variable like now; keep `subnet_ids` as before.

In `for_each` try to use `ip_address` (if not empty) or `subnet_ids` converted in the same structure as `ip_address`.

Make sure to show the usage of both variables in examples.

2024-08-16 19:46 UTC, antonbabenko commented on modules/resolver-endpoints/main.tf
> +      ip        = ip_address.value.ip
```suggestion
      ip        = lookup(ip_address.value, "ip", null)
```

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_resolver_endpoint#ip - here it says that "ip" is optional.

2024-08-16 19:46 UTC, antonbabenko commented on modules/resolver-endpoints/variables.tf
> +  type = list(object({
```suggestion
  type = list(map(string)) # or list(any)
```

2024-08-31 02:46 UTC, antonbabenko approved these changes

2024-08-31 02:46 UTC, merged

2024-08-31 02:47 UTC, antonbabenko commented
This PR is included in version 4.0.1 :tada: