feat(zones): Add primary name server to outputs
terraform-aws-modules/terraform-aws-route53 pull request #108
Opened 2024-06-17 13:29 UTC by sapphireqt

## Description
One more output has been added in zones module in this PR: `primary_name_server`.

## Motivation and Context
This new output could be useful if SOA record modification is required in dependent modules.

## Breaking Changes
No breaking changes

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

2024-07-11 07:30 UTC, marko-fabry approved these changes

2024-08-16 19:51 UTC, antonbabenko requested changes
Please update `versions.tf` to require [AWS provider version 4.36.0](primary_name_server) or newer since this is when `primary_name_server` attribute was introduced.

It will have to be a major release.

2024-08-17 12:06 UTC, sapphireqt commented
Thank you for for your review. I've updated the version of aws provider at zones module.

2024-08-17 23:46 UTC, antonbabenko approved these changes

2024-08-17 23:47 UTC, merged

2024-08-17 23:48 UTC, antonbabenko commented
This PR is included in version 4.0.0 :tada: