feat: Add zone-cross-account-vpc-association submodule
terraform-aws-modules/terraform-aws-route53 pull request #109
Opened 2024-07-02 07:46 UTC by jramosf

## Description
This PR add a new submodule to create cross-account Route53 VPC associations, using the authorization association resources (https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-associate-vpcs-different-accounts.html)

## Motivation and Context
For cross-account AWS documentation generally recommends using Route53Resolver. The API endpoint [CreateVPCAssociationAuthorization](https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateVPCAssociationAuthorization.html) is not even implemented in AWS Console.

However, this option is simpler as it does not require explicit resolver infrastructure (living within the VPC with specific Elastic Network Interfaces) and it does not involve cost on paying the Route53Resolver infrastructure, which makes it ideal for (most) cases.

## Breaking Changes
N/A

## How Has This Been Tested?
* [x]  I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
* [x]  I have tested and validated these changes using one or more of the provided `examples/*` projects

* [x]  I have executed `pre-commit run -a` on my pull request
>

2024-07-26 12:40 UTC, jramosf commented
@antonbabenko this is ready to review and I confirmed working. Please take a look whenever you can. Thanks!

2024-08-16 20:14 UTC, antonbabenko requested changes
Looks pretty good. There are some small comments.

2024-08-16 20:14 UTC, antonbabenko commented on modules/zone-cross-account-vpc-association/variables.tf
> +}
Please, add `default` value, too.

2024-08-16 20:14 UTC, antonbabenko commented on modules/zone-cross-account-vpc-association/variables.tf
> +  description = "Map of associations indicating zone_id and vpc_id to associate. The region is optional and will be derived from the provider if not passed."
```suggestion
  description = "Map of associations indicating zone_id and vpc_id to associate."
```

2024-08-16 20:14 UTC, antonbabenko commented on modules/zone-cross-account-vpc-association/outputs.tf
> +  description = "Unique ID of Route53 VPC association authorizations"
```suggestion
  description = "ID of Route53 VPC association authorizations"
```

2024-08-16 20:14 UTC, antonbabenko commented on modules/zone-cross-account-vpc-association/outputs.tf
> +  description = "Unique ID of Route53 VPC association"
```suggestion
  description = "ID of Route53 VPC association"
```

2024-08-16 20:14 UTC, antonbabenko commented on modules/zone-cross-account-vpc-association/outputs.tf
> +}
Please add one more output - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_zone_association#owning_account

2024-08-16 20:14 UTC, antonbabenko commented on examples/complete/main.tf
> +module "zone_cross_account_vpc_association" {
Please add one more module block as an example when `create = false`

2024-08-16 20:14 UTC, antonbabenko commented on examples/complete/main.tf
> +provider "aws" {
Please add newlines between blocks.

2024-08-19 14:16 UTC, jramosf commented
HI @antonbabenko , I've performed all changes requested and rebased the branch. Thanks,

2024-08-19 18:23 UTC, antonbabenko commented on examples/complete/main.tf
> +  version  = "~> 5.0"
```suggestion
  version = "~> 5.0"

  provider = aws.second_account
```

2024-08-19 18:25 UTC, antonbabenko commented on modules/zone-cross-account-vpc-association/versions.tf
> +      configuration_aliases = [ aws.r53_owner, aws.vpc_owner ]
```suggestion
      configuration_aliases = [aws.r53_owner, aws.vpc_owner]
```

2024-08-19 18:28 UTC, antonbabenko commented on modules/zone-cross-account-vpc-association/main.tf
> +  provider = aws.r53_owner
```suggestion
  provider = aws.r53_owner

```

2024-08-19 18:28 UTC, antonbabenko commented on modules/zone-cross-account-vpc-association/main.tf
> +  provider   = aws.vpc_owner
```suggestion
  for_each = aws_route53_vpc_association_authorization.this

  provider   = aws.vpc_owner

```

2024-08-20 06:07 UTC, jramosf commented
@antonbabenko rebased and changes ready

2024-08-31 02:50 UTC, antonbabenko requested changes
Please fix the failing CI

2024-09-02 07:24 UTC, jramosf commented
Hi @antonbabenko , it seems I encountered some bug with Terraform.

To fix the following error:
```terraform
│ Error: Provider configuration not present
│ 
│ To work with aws_route53_zone_association.this its original provider configuration at provider["registry.terraform.io/hashicorp/aws"].vpc_owner is required, but it has been removed. This occurs when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy
│ aws_route53_zone_association.this, after which you can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with aws_route53_vpc_association_authorization.this its original provider configuration at provider["registry.terraform.io/hashicorp/aws"].r53_owner is required, but it has been removed. This occurs when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy
│ aws_route53_vpc_association_authorization.this, after which you can remove the provider configuration again.
```
I put the following in `versions.tf`:
```terraform
provider "aws" {
  alias = "r53_owner"
}

provider "aws" {
  alias = "vpc_owner"
}
```
This makes the `terraform fmt` and `terraform validate` to pass cleanly in both `modules/zone-cross-account-vpc-association` and `example/complete` (exit code 0), however the following warning is now shown in `example/complete` (not in the module itself):
```terraform
│ Warning: Redundant empty provider block
│ 
│   on ../../modules/zone-cross-account-vpc-association/versions.tf line 13:
│   13: provider "aws" {
│ 
│ Earlier versions of Terraform used empty provider blocks ("proxy provider configurations") for child modules to declare their need to be passed a provider configuration by their callers. That approach was ambiguous and is now deprecated.
│ 
│ If you control this module, you can migrate to the new declaration syntax by removing all of the empty provider "aws" blocks and then adding or updating an entry like the following to the required_providers block of module.zone_cross_account_vpc_association:
│     aws = {
│       source = "hashicorp/aws"
│       configuration_aliases = [
│         aws.r53_owner,
│         aws.vpc_owner,
│       ]
│     }
│ 
```

I have tried with latest Terraform version (`1.9.5` at the moment), but it seems it's a problem with Terraform itself on how the `validate` command evaluates this, I might reach out to them to check on this.

**Nevertheless, the pipeline should pass so it's ready to review. Thanks!**

2024-09-03 06:42 UTC, jramosf commented
<img width="747" alt="image" src="https://github.com/user-attachments/assets/4fba5246-274a-4b84-9a69-6c7392d4719b">
`pre-commit run --all-files` is now passing cleanly.

2024-09-03 20:31 UTC, antonbabenko approved these changes
Fixed the rest. Thank you!

2024-09-03 20:32 UTC, merged

2024-09-03 20:32 UTC, antonbabenko commented
This PR is included in version 4.1.0 :tada: