feat(modules/zone): complex variable types
terraform-aws-modules/terraform-aws-route53 pull request #111
Opened 2024-09-16 11:09 UTC by kevcube

2024-10-17 07:36 UTC, kevcube commented
Not stale

2024-11-27 17:23 UTC, BeyondEvil commented
This is really nice!

Any chance of getting your input here @antonbabenko ?

2024-11-27 18:34 UTC, antonbabenko commented
> This is really nice!
> 
> Any chance of getting your input here @antonbabenko ?

Yes, I plan to get back to this and many other PRs in terraform-aws-modules after AWS reinvent.

2025-01-07 09:34 UTC, BeyondEvil commented
How was re:invent @antonbabenko ? 😅

2025-01-07 21:15 UTC, antonbabenko requested changes
These changes certainly look like an improvement, but it is essential to keep backward compatibility in mind and don't introduce breaking changes.

Please make sure that the code in `examples/complete` works as expected (now I see the error: `each.value.vpc is null Cannot use a null value in for_each.`).

2025-01-07 21:18 UTC, antonbabenko commented
> How was re:invent @antonbabenko ? 😅

@BeyondEvil Thanks for asking, it went well - https://www.youtube.com/watch?v=fX7c2GGqTWs 😅

2025-01-08 07:10 UTC, BeyondEvil commented
> > How was re:invent @antonbabenko ? 😅
> 
> @BeyondEvil Thanks for asking, it went well - https://www.youtube.com/watch?v=fX7c2GGqTWs 😅

Oh nice! I'll have a look. 👍

2025-02-08 00:31 UTC, BeyondEvil commented
ping @kevcube

2025-02-08 00:32 UTC, BeyondEvil commented
not stale

2025-03-12 09:57 UTC, BeyondEvil commented
not stale

2025-03-29 21:36 UTC, bryantbiggs commented on modules/zones/main.tf
> +  name          = coalesce(each.value.domain_name, each.key)
```suggestion
  name          = try(each.value.domain_name, each.key)
```

2025-03-29 21:38 UTC, bryantbiggs commented on modules/zones/main.tf
> +    for_each = each.value.vpc
not quite, I think we need more guards/checks

```suggestion
    for_each = each.value.vpc != null ? each.value.vpc : []
```

2025-05-09 00:19 UTC, closed without merging

2025-09-20 13:12 UTC, antonbabenko commented
This issue has been resolved in version 6.0.0 :tada: