Feature/added weighted routing policy
terraform-aws-modules/terraform-aws-route53 pull request #20
Opened 2020-12-12 03:21 UTC by nashvan

## Description
Added weighted routing policy as an option to the module

## Motivation and Context

## Breaking Changes

## How Has This Been Tested?

2020-12-12 09:30 UTC, antonbabenko requested changes

2020-12-12 09:30 UTC, antonbabenko commented on modules/records/main.tf
> +      weight                 = lookup(each.value.weighted_routing_policy,"weight", null)
weight is required, so a lookup is not needed.

2020-12-12 09:30 UTC, antonbabenko commented on examples/complete/main.tf
> +      set_identifier = "develop"
Where is this used?

2020-12-12 10:24 UTC, nashvan commented on examples/complete/main.tf
> +      set_identifier = "develop"
@antonbabenko  this ius just an example add into the example amin.tf 
happy to remove it if that makes it better?

2020-12-12 13:33 UTC, nashvan commented on modules/records/main.tf
> +      weight                 = lookup(each.value.weighted_routing_policy,"weight", null)
@antonbabenko Removed lookup here, good point

2020-12-12 13:53 UTC, nashvan commented on examples/complete/main.tf
> +      set_identifier = "develop"
removed that from the example

2020-12-12 14:15 UTC, antonbabenko commented on examples/complete/main.tf
> +      set_identifier = "develop"
1. `set_identifier` is an argument to the resource (see the docs), so it should be supported by the module.
2. Example code was almost perfect, so I am not sure why you removed it.
3. Update formatting by running `pre-commit run -a`

2020-12-13 12:02 UTC, nashvan commented on examples/complete/main.tf
> +      set_identifier = "develop"
@antonbabenko 
bash: pre-commit: command not found
I am I running it wrong or?

2020-12-16 04:41 UTC, closed without merging