add option to overwrite existing records
terraform-aws-modules/terraform-aws-route53 pull request #43
Opened 2021-06-11 13:09 UTC by DayneD89

## Description
Adds a variable to allow exisitng records to be recoved. By default it is false, but allows users of the module to pass this argument in.

## Motivation and Context
Corrently there is no way to use the module to overwrite existing records, which is what I'm trying to use it for. 

## Breaking Changes
No breaking changes. It is set to false by default on the underlying resource so this doesn't change that. 

## How Has This Been Tested?
Little testing should be needed for this simple change, but I have built my project with this change to verify that it passes in the variable.

2021-06-11 20:51 UTC, antonbabenko requested changes

2021-06-11 20:51 UTC, antonbabenko commented on modules/records/main.tf
> +  allow_overwrite = var.allow_overwrite
Please implement this argument as other arguments (using `lookup`) to allow control for individual records.

2021-06-14 19:43 UTC, 7adityaraj commented on modules/records/variables.tf
> +variable "allow_overwrite" {
do we need this variable?

2021-06-14 19:48 UTC, antonbabenko commented on modules/records/variables.tf
> +variable "allow_overwrite" {
No, @DayneD89 please remove this one here and in README.

2021-08-13 16:49 UTC, merged

2021-08-13 16:56 UTC, antonbabenko commented
Thanks @DayneD89 @dayne !

[v2.2.0](https://github.com/terraform-aws-modules/terraform-aws-route53/releases/v2.2.0) has been just released with this PR merged.