feat: add resolver rule association module
terraform-aws-modules/terraform-aws-route53 pull request #70
Opened 2022-05-20 08:39 UTC by SlavaSubotskiy

## Description
Resolver rule association module was added

## Motivation and Context
It is used to create one or more resolver rule associations

## Breaking Changes
Clear addition

## How Has This Been Tested?
- tflint
- terraform fmt
- real resolver rule associations created

2022-05-25 08:05 UTC, SlavaSubotskiy commented
@antonbabenko kindly ask you to review this Pull Request

2022-05-25 08:28 UTC, antonbabenko requested changes
Please add a complete and working example for this module in `examples` (create minimal VPC using the VPC module) and create valid resources for a couple of rules, too.

PS: In the future, we may have to expand this module to support individual types of `aws_route53_resolver_*` to offer a bigger set of functionality.

2022-05-25 08:28 UTC, antonbabenko commented on modules/resolver-rule-associations/main.tf
> +  name             = try(each.value.name, each.key, null)
`each.key` will be always present, but `name` is an optional argument.

```suggestion
  name             = try(each.value.name, null)
```

2022-05-25 08:28 UTC, antonbabenko commented on modules/resolver-rule-associations/main.tf
> +  resolver_rule_id = lookup(each.value, "resolver_rule_id", null)
```suggestion
  resolver_rule_id = each.value.resolver_rule_id
```

`resolver_rule_id` is required.

2022-05-25 08:28 UTC, antonbabenko commented on modules/resolver-rule-associations/main.tf
> +  for_each = var.create ? var.resolver_rule_associations : tomap({})
```suggestion
  for_each = { for k, v in var.resolver_rule_associations : k => v if var.create }
```

This is the right way to write it in `for_each` instead of using `tomap()`. This way it is not going to work always like you expected (in Terraform 0.13 and 0.14+).

2022-05-27 11:26 UTC, SlavaSubotskiy commented
> Please add a complete and working example for this module in `examples` (create minimal VPC using the VPC module) and create valid resources for a couple of rules, too.

@antonbabenko example was added, kindly ask you to review PR again.

2022-05-27 20:14 UTC, merged

2022-05-27 20:14 UTC, antonbabenko commented
Thanks @SlavaSubotskiy for this PR!

2022-05-27 20:15 UTC, antonbabenko commented
This PR is included in version 2.8.0 :tada: